Repository eiffel-community/eiffelevents-sdk-dotnet, pull requests merged in 2021-12, with the labels that each got.

#4 Create build workflow (#3).
  dotnet.yml
Labels: CI support

#8 Move dotnet workflow file to .githube/workflows
  .github/workflows/dotnet.yml
Labels: bug, CI support

#6 Enhance readme files
  README.md
  clients/README.md
Labels: documentation, enhancement

#10 Clients directory restructuring
  Dockerfile
  Eiffel.Net.sln
  Makefile
  README.md
  docs/README.md
  examples/EiffelClient.BasicPublisher/EiffelClient.BasicPublisher.csproj
  examples/EiffelClient.BasicPublisher/Program.cs
  examples/EiffelClient.PublisherOne/EiffelClient.PublisherOne.csproj
  examples/EiffelClient.PublisherOne/Models/ActivityCanceled.cs
  examples/EiffelClient.PublisherOne/Models/ActivityFinished.cs
  examples/EiffelClient.PublisherOne/Models/ActivityStarted.cs
  examples/EiffelClient.PublisherOne/Models/ActivityTriggered.cs
  examples/EiffelClient.PublisherOne/Models/AnnouncementPublished.cs
  examples/EiffelClient.PublisherOne/Models/ArtifactCreated.cs
  examples/EiffelClient.PublisherOne/Models/ArtifactPublished.cs
  examples/EiffelClient.PublisherOne/Models/ArtifactReused.cs
  examples/EiffelClient.PublisherOne/Models/Client.cs
  examples/EiffelClient.PublisherOne/Models/CompositionDefined.cs
  examples/EiffelClient.PublisherOne/Models/ConfidenceLevelModified.cs
  examples/EiffelClient.PublisherOne/Models/EnvironmentDefined.cs
  examples/EiffelClient.PublisherOne/Models/FlowContextDefined.cs
  examples/EiffelClient.PublisherOne/Models/IssueDefined.cs
  examples/EiffelClient.PublisherOne/Models/IssueVerified.cs
  examples/EiffelClient.PublisherOne/Models/SourceChangeCreated.cs
  examples/EiffelClient.PublisherOne/Models/SourceChangeSubmitted.cs
  examples/EiffelClient.PublisherOne/Models/TestCaseCanceled.cs
  examples/EiffelClient.PublisherOne/Models/TestCaseFinished.cs
  examples/EiffelClient.PublisherOne/Models/TestCaseStarted.cs
  examples/EiffelClient.PublisherOne/Models/TestCaseTriggered.cs
  examples/EiffelClient.PublisherOne/Models/TestExecutionRecipeCollectionCreated.cs
  examples/EiffelClient.PublisherOne/Models/TestSuiteFinished.cs
  examples/EiffelClient.PublisherOne/Models/TestSuiteStarted.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/EiffelClient.SubscriberOne.csproj
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberOne/appsettings.Development.json
  examples/EiffelClient.SubscriberTwo/EiffelClient.SubscriberTwo.csproj
  examples/EiffelClient.SubscriberTwo/Program.cs
  examples/EiffelClient.SubscriberTwo/appsettings.Development.json
  examples/README.md
  examples/deploy/.env
  examples/deploy/.gitignore
  examples/deploy/docker-compose.yml
  examples/deploy/services/rabbitmq/rabbitmq.conf
  scripts/docker.mk
Labels: refactoring

#14 refactor Eiffel links serialization (issue #13)
  src/EiffelEvents.Net/Common/JsonHelper.cs
  src/EiffelEvents.Net/Events/Core/Links/IEiffelSerializedLink.cs
  src/EiffelEvents.Net/Events/Core/Links/IEiffelSerializedLinkCollection.cs
  src/EiffelEvents.Net/Events/Edition-Paris/Shared/EiffelEvent.cs
  src/EiffelEvents.Net/Events/Edition-Paris/Shared/EiffelSerializedLink.cs
  src/EiffelEvents.Net/Events/Edition-Paris/Shared/EiffelSerializedLinkCollection.cs
Labels: refactoring

#19 Add design documents
  README.md
  docs/DocFX-helper.md
  docs/README.md
  docs/docfx_project/articles/architecture-eiffelevents.md
  docs/docfx_project/articles/architecture-rabbitmq-client.md
  docs/docfx_project/articles/architecture.md
  docs/docfx_project/articles/implement-event.md
  docs/docfx_project/articles/index.md
  docs/docfx_project/articles/intro.md
  docs/docfx_project/articles/toc.yml
  docs/docfx_project/docfx.json
  docs/docfx_project/images/high-level-design.svg
  docs/docfx_project/images/queue-duplication.svg
  docs/docfx_project/images/rabbitmq-communication.svg
  docs/docfx_project/images/sdk-structure.svg
  docs/docfx_project/images/sign-event.svg
  docs/docfx_project/images/unique-queue.svg
  docs/docfx_project/images/verify-signature.svg
  docs/docfx_project/index.md
  docs/docfx_project/toc.yml
  docs/image-src/high-level-design.drawio
  docs/image-src/queue-duplication.drawio
  docs/image-src/rabbitmq-communication.drawio
  docs/image-src/sdk-structure.drawio
  docs/image-src/sign-event.drawio
  docs/image-src/unique-queue.drawio
  docs/image-src/verify-signature.drawio
Labels: documentation, enhancement

#44 Update build workflow to run on development branch
  .github/workflows/dotnet.yml
Labels: CI support
