Repository eiffel-community/eiffelevents-sdk-dotnet, pull requests merged in 2022-01, with the labels that each got.

#49 Lyon add eiffel activity started
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ActivityStarted.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityStartedEvent/EiffelActivityStartedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityStartedEvent/EiffelActivityStartedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityStartedEvent/EiffelActivityStartedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityStartedEvent/EiffelActivityStartedMeta.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Data/EiffelLiveLog.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelActivityStartedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelActivityStartedEventFixture.cs
Labels: feature

#51 Lyon add eiffel artifact created
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ArtifactCreated.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactCreatedEvent/EiffelArtifactCreatedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactCreatedEvent/EiffelArtifactCreatedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactCreatedEvent/EiffelArtifactCreatedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactCreatedEvent/EiffelArtifactCreatedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelArtifactCreatedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelArtifactCreatedEventFixture.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Paris/EiffelArtifactCreatedEventFixture.cs
Labels: feature

#52 Lyon add artifact published
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ArtifactPublished.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactPublishedEvent/EiffelArtifactPublishedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactPublishedEvent/EiffelArtifactPublishedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactPublishedEvent/EiffelArtifactPublishedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactPublishedEvent/EiffelArtifactPublishedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelArtifactPublishedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelArtifactPublishedEventFixture.cs
Labels: feature

#57 Lyon add environment defined
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/EnvironmentDefined.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedMeta.cs
  src/EiffelEvents.Net/Events/Edition-Paris/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedData.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelEnvironmentDefinedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelEnvironmentDefinedEventFixture.cs
Labels: feature

#59 Lyon add source change created
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/SourceChangeCreated.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeCreatedEvent/EiffelSourceChangeCreatedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeCreatedEvent/EiffelSourceChangeCreatedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeCreatedEvent/EiffelSourceChangeCreatedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeCreatedEvent/EiffelSourceChangeCreatedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelSourceChangeCreatedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelSourceChangeCreatedEventFixture.cs
Labels: feature

#61 Lyon add eiffel source change submitted
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/SourceChangeSubmitted.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeSubmittedEvent/EiffelSourceChangeSubmittedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeSubmittedEvent/EiffelSourceChangeSubmittedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeSubmittedEvent/EiffelSourceChangeSubmittedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeSubmittedEvent/EiffelSourceChangeSubmittedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelSourceChangeSubmittedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelSourceChangeSubmittedEventFixture.cs
Labels: feature

#60 Lyon add flow context defined
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/FlowContextDefined.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelFlowContextDefinedEvent/EiffelFlowContextDefinedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelFlowContextDefinedEvent/EiffelFlowContextDefinedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelFlowContextDefinedEvent/EiffelFlowContextDefinedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelFlowContextDefinedEvent/EiffelFlowContextDefinedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelFlowContextDefinedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelFlowContextDefinedEventFixture.cs
Labels: feature

#62 Lyon add eiffel test case triggered
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestCaseTriggered.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseTriggeredEvent/EiffelTestCaseTriggeredData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseTriggeredEvent/EiffelTestCaseTriggeredEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseTriggeredEvent/EiffelTestCaseTriggeredLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseTriggeredEvent/EiffelTestCaseTriggeredMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestCaseTriggeredEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestCaseTriggeredEventFixture.cs
Labels: feature

#65 Lyon add eiffel test case started
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestCaseStarted.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseStartedEvent/EiffelTestCaseStartedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseStartedEvent/EiffelTestCaseStartedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseStartedEvent/EiffelTestCaseStartedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseStartedEvent/EiffelTestCaseStartedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestCaseStartedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestCaseStartedEventFixture.cs
Labels: feature

#66 Lyon add eiffel test case finished
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestCaseFinished.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestCaseFinishedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestCaseFinishedEventFixture.cs
Labels: feature

#67 Lyon add eiffel test suite started
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestSuiteStarted.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestSuiteStartedEvent/EiffelTestSuiteStartedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestSuiteStartedEvent/EiffelTestSuiteStartedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestSuiteStartedEvent/EiffelTestSuiteStartedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestSuiteStartedEvent/EiffelTestSuiteStartedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestSuiteStartedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestSuiteStartedEventFixture.cs
Labels: feature

#69 Lyon add eiffel issue verified
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/IssueVerified.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelIssueVerifiedEvent/EiffelIssueVerifiedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelIssueVerifiedEvent/EiffelIssueVerifiedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelIssueVerifiedEvent/EiffelIssueVerifiedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelIssueVerifiedEvent/EiffelIssueVerifiedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelIssueVerifiedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelIssueVerifiedEventFixture.cs
Labels: feature

#71 Lyon add eiffel test execution recipe collection created
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestExecutionRecipeCollectionCreated.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestExecutionRecipeCollectionCreatedEvent/EiffelTestExecutionRecipeCollectionCreatedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestExecutionRecipeCollectionCreatedEvent/EiffelTestExecutionRecipeCollectionCreatedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestExecutionRecipeCollectionCreatedEvent/EiffelTestExecutionRecipeCollectionCreatedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestExecutionRecipeCollectionCreatedEvent/EiffelTestExecutionRecipeCollectionCreatedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestExecutionRecipeCollectionCreatedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestExecutionRecipeCollectionCreatedEventFixture.cs
Labels: feature

#72 Lyon add eiffel announcement published
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/AnnouncementPublished.cs
  examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
  examples/EiffelClient.PublisherOne/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/EiffelClient.SubscriberTwo/Program.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelAnnouncementPublishedEvent/EiffelAnnouncementPublishedData.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelAnnouncementPublishedEvent/EiffelAnnouncementPublishedEvent.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelAnnouncementPublishedEvent/EiffelAnnouncementPublishedLinks.cs
  src/EiffelEvents.Net/Events/Edition-Lyon/EiffelAnnouncementPublishedEvent/EiffelAnnouncementPublishedMeta.cs
  tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelAnnouncementPublishedEventTests.cs
  tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelAnnouncementPublishedEventFixture.cs
Labels: feature

#74 Lyon update docs
  README.md
  docs/docfx_project/articles/architecture-eiffelevents.md
  docs/docfx_project/articles/architecture-rabbitmq-client.md
  examples/EiffelClient.BasicPublisher/Program.cs
  examples/EiffelClient.SubscriberOne/Program.cs
  examples/README.md
Labels: documentation

#76 Fix queue durability
  docs/docfx_project/articles/architecture-rabbitmq-client.md
  src/EiffelEvents.RabbitMq.Client/Common/RabbitMqWrapper.cs
Labels: enhancement
